### ISSUE TITLE
how to access the service

### ISSUE THREAD

**Issue by lewis-kori** [BBVA/timecop#19]
Great service ,how do i access the webservice API, do i have to download the application and run it locally or is there a way i can just access the service online?

**Comment by SIPVZ** [comment]
Hi!

I'll attach a quick start guide in the readme. But in the meantime, I'll explain you the simplest option:  deploy a docker with timecop deployed. This is the link:
[](https://cloud.docker.com/repository/docker/trakuo/timecop
)

Run docker publishing port 80:
`docker run -d --name timecoprunning -p 3000:3000 timecop `
and finally, you can use the web page located in the source code /web_pages to use it.

Best regards.

**Comment by lewis-kori** [comment]
thank you
